/** ISO2 → { es, fr } display names. English comes from country-state-city. */
export const COUNTRY_NAMES: Record<string, { es: string; fr: string }> = {
  AD: { es: "Andorra", fr: "Andorre" },
  AE: { es: "Emiratos Árabes Unidos", fr: "Émirats arabes unis" },
  AF: { es: "Afganistán", fr: "Afghanistan" },
  AG: { es: "Antigua y Barbuda", fr: "Antigua-et-Barbuda" },
  AI: { es: "Anguila", fr: "Anguilla" },
  AL: { es: "Albania", fr: "Albanie" },
  AM: { es: "Armenia", fr: "Arménie" },
  AO: { es: "Angola", fr: "Angola" },
  AQ: { es: "Antártida", fr: "Antarctique" },
  AR: { es: "Argentina", fr: "Argentine" },
  AS: { es: "Samoa Americana", fr: "Samoa américaines" },
  AT: { es: "Austria", fr: "Autriche" },
  AU: { es: "Australia", fr: "Australie" },
  AW: { es: "Aruba", fr: "Aruba" },
  AX: { es: "Islas Åland", fr: "Îles Åland" },
  AZ: { es: "Azerbaiyán", fr: "Azerbaïdjan" },
  BA: { es: "Bosnia y Herzegovina", fr: "Bosnie-Herzégovine" },
  BB: { es: "Barbados", fr: "Barbade" },
  BD: { es: "Bangladés", fr: "Bangladesh" },
  BE: { es: "Bélgica", fr: "Belgique" },
  BF: { es: "Burkina Faso", fr: "Burkina Faso" },
  BG: { es: "Bulgaria", fr: "Bulgarie" },
  BH: { es: "Baréin", fr: "Bahreïn" },
  BI: { es: "Burundi", fr: "Burundi" },
  BJ: { es: "Benín", fr: "Bénin" },
  BL: { es: "San Bartolomé", fr: "Saint-Barthélemy" },
  BM: { es: "Bermudas", fr: "Bermudes" },
  BN: { es: "Brunéi", fr: "Brunéi Darussalam" },
  BO: { es: "Bolivia", fr: "Bolivie" },
  BQ: { es: "Caribe Neerlandés", fr: "Pays-Bas caribéens" },
  BR: { es: "Brasil", fr: "Brésil" },
  BS: { es: "Bahamas", fr: "Bahamas" },
  BT: { es: "Bután", fr: "Bhoutan" },
  BV: { es: "Isla Bouvet", fr: "Île Bouvet" },
  BW: { es: "Botsuana", fr: "Botswana" },
  BY: { es: "Bielorrusia", fr: "Biélorussie" },
  BZ: { es: "Belice", fr: "Belize" },
  CA: { es: "Canadá", fr: "Canada" },
  CC: { es: "Islas Cocos", fr: "Îles Cocos" },
  CD: { es: "República Democrática del Congo", fr: "République démocratique du Congo" },
  CF: { es: "República Centroafricana", fr: "République centrafricaine" },
  CG: { es: "Congo", fr: "Congo" },
  CH: { es: "Suiza", fr: "Suisse" },
  CI: { es: "Costa de Marfil", fr: "Côte d'Ivoire" },
  CK: { es: "Islas Cook", fr: "Îles Cook" },
  CL: { es: "Chile", fr: "Chili" },
  CM: { es: "Camerún", fr: "Cameroun" },
  CN: { es: "China", fr: "Chine" },
  CO: { es: "Colombia", fr: "Colombie" },
  CR: { es: "Costa Rica", fr: "Costa Rica" },
  CU: { es: "Cuba", fr: "Cuba" },
  CV: { es: "Cabo Verde", fr: "Cap-Vert" },
  CW: { es: "Curazao", fr: "Curaçao" },
  CX: { es: "Isla de Navidad", fr: "Île Christmas" },
  CY: { es: "Chipre", fr: "Chypre" },
  CZ: { es: "República Checa", fr: "Tchéquie" },
  DE: { es: "Alemania", fr: "Allemagne" },
  DJ: { es: "Yibuti", fr: "Djibouti" },
  DK: { es: "Dinamarca", fr: "Danemark" },
  DM: { es: "Dominica", fr: "Dominique" },
  DO: { es: "República Dominicana", fr: "République dominicaine" },
  DZ: { es: "Argelia", fr: "Algérie" },
  EC: { es: "Ecuador", fr: "Équateur" },
  EE: { es: "Estonia", fr: "Estonie" },
  EG: { es: "Egipto", fr: "Égypte" },
  EH: { es: "Sáhara Occidental", fr: "Sahara occidental" },
  ER: { es: "Eritrea", fr: "Érythrée" },
  ES: { es: "España", fr: "Espagne" },
  ET: { es: "Etiopía", fr: "Éthiopie" },
  FI: { es: "Finlandia", fr: "Finlande" },
  FJ: { es: "Fiyi", fr: "Fidji" },
  FK: { es: "Islas Malvinas", fr: "Îles Malouines" },
  FM: { es: "Micronesia", fr: "Micronésie" },
  FO: { es: "Islas Feroe", fr: "Îles Féroé" },
  FR: { es: "Francia", fr: "France" },
  GA: { es: "Gabón", fr: "Gabon" },
  GB: { es: "Reino Unido", fr: "Royaume-Uni" },
  GD: { es: "Granada", fr: "Grenade" },
  GE: { es: "Georgia", fr: "Géorgie" },
  GF: { es: "Guayana Francesa", fr: "Guyane" },
  GG: { es: "Guernsey", fr: "Guernesey" },
  GH: { es: "Ghana", fr: "Ghana" },
  GI: { es: "Gibraltar", fr: "Gibraltar" },
  GL: { es: "Groenlandia", fr: "Groenland" },
  GM: { es: "Gambia", fr: "Gambie" },
  GN: { es: "Guinea", fr: "Guinée" },
  GP: { es: "Guadalupe", fr: "Guadeloupe" },
  GQ: { es: "Guinea Ecuatorial", fr: "Guinée équatoriale" },
  GR: { es: "Grecia", fr: "Grèce" },
  GS: { es: "Georgia del Sur e Islas Sandwich del Sur", fr: "Géorgie du Sud-et-les Îles Sandwich du Sud" },
  GT: { es: "Guatemala", fr: "Guatemala" },
  GU: { es: "Guam", fr: "Guam" },
  GW: { es: "Guinea-Bisáu", fr: "Guinée-Bissau" },
  GY: { es: "Guyana", fr: "Guyana" },
  HK: { es: "Hong Kong", fr: "Hong Kong" },
  HM: { es: "Islas Heard y McDonald", fr: "Îles Heard-et-MacDonald" },
  HN: { es: "Honduras", fr: "Honduras" },
  HR: { es: "Croacia", fr: "Croatie" },
  HT: { es: "Haití", fr: "Haïti" },
  HU: { es: "Hungría", fr: "Hongrie" },
  ID: { es: "Indonesia", fr: "Indonésie" },
  IE: { es: "Irlanda", fr: "Irlande" },
  IL: { es: "Israel", fr: "Israël" },
  IM: { es: "Isla de Man", fr: "Île de Man" },
  IN: { es: "India", fr: "Inde" },
  IO: { es: "Territorio Británico del Océano Índico", fr: "Territoire britannique de l'océan Indien" },
  IQ: { es: "Irak", fr: "Irak" },
  IR: { es: "Irán", fr: "Iran" },
  IS: { es: "Islandia", fr: "Islande" },
  IT: { es: "Italia", fr: "Italie" },
  JE: { es: "Jersey", fr: "Jersey" },
  JM: { es: "Jamaica", fr: "Jamaïque" },
  JO: { es: "Jordania", fr: "Jordanie" },
  JP: { es: "Japón", fr: "Japon" },
  KE: { es: "Kenia", fr: "Kenya" },
  KG: { es: "Kirguistán", fr: "Kirghizistan" },
  KH: { es: "Camboya", fr: "Cambodge" },
  KI: { es: "Kiribati", fr: "Kiribati" },
  KM: { es: "Comoras", fr: "Comores" },
  KN: { es: "San Cristóbal y Nieves", fr: "Saint-Kitts-et-Nevis" },
  KP: { es: "Corea del Norte", fr: "Corée du Nord" },
  KR: { es: "Corea del Sur", fr: "Corée du Sud" },
  KW: { es: "Kuwait", fr: "Koweït" },
  KY: { es: "Islas Caimán", fr: "Îles Caïmans" },
  KZ: { es: "Kazajistán", fr: "Kazakhstan" },
  LA: { es: "Laos", fr: "Laos" },
  LB: { es: "Líbano", fr: "Liban" },
  LC: { es: "Santa Lucía", fr: "Sainte-Lucie" },
  LI: { es: "Liechtenstein", fr: "Liechtenstein" },
  LK: { es: "Sri Lanka", fr: "Sri Lanka" },
  LR: { es: "Liberia", fr: "Libéria" },
  LS: { es: "Lesoto", fr: "Lesotho" },
  LT: { es: "Lituania", fr: "Lituanie" },
  LU: { es: "Luxemburgo", fr: "Luxembourg" },
  LV: { es: "Letonia", fr: "Lettonie" },
  LY: { es: "Libia", fr: "Libye" },
  MA: { es: "Marruecos", fr: "Maroc" },
  MC: { es: "Mónaco", fr: "Monaco" },
  MD: { es: "Moldavia", fr: "Moldavie" },
  ME: { es: "Montenegro", fr: "Monténégro" },
  MF: { es: "San Martín", fr: "Saint-Martin" },
  MG: { es: "Madagascar", fr: "Madagascar" },
  MH: { es: "Islas Marshall", fr: "Îles Marshall" },
  MK: { es: "Macedonia del Norte", fr: "Macédoine du Nord" },
  ML: { es: "Malí", fr: "Mali" },
  MM: { es: "Myanmar", fr: "Myanmar" },
  MN: { es: "Mongolia", fr: "Mongolie" },
  MO: { es: "Macao", fr: "Macao" },
  MP: { es: "Islas Marianas del Norte", fr: "Îles Mariannes du Nord" },
  MQ: { es: "Martinica", fr: "Martinique" },
  MR: { es: "Mauritania", fr: "Mauritanie" },
  MS: { es: "Montserrat", fr: "Montserrat" },
  MT: { es: "Malta", fr: "Malte" },
  MU: { es: "Mauricio", fr: "Maurice" },
  MV: { es: "Maldivas", fr: "Maldives" },
  MW: { es: "Malaui", fr: "Malawi" },
  MX: { es: "México", fr: "Mexique" },
  MY: { es: "Malasia", fr: "Malaisie" },
  MZ: { es: "Mozambique", fr: "Mozambique" },
  NA: { es: "Namibia", fr: "Namibie" },
  NC: { es: "Nueva Caledonia", fr: "Nouvelle-Calédonie" },
  NE: { es: "Níger", fr: "Niger" },
  NF: { es: "Isla Norfolk", fr: "Île Norfolk" },
  NG: { es: "Nigeria", fr: "Nigéria" },
  NI: { es: "Nicaragua", fr: "Nicaragua" },
  NL: { es: "Países Bajos", fr: "Pays-Bas" },
  NO: { es: "Noruega", fr: "Norvège" },
  NP: { es: "Nepal", fr: "Népal" },
  NR: { es: "Nauru", fr: "Nauru" },
  NU: { es: "Niue", fr: "Niue" },
  NZ: { es: "Nueva Zelanda", fr: "Nouvelle-Zélande" },
  OM: { es: "Omán", fr: "Oman" },
  PA: { es: "Panamá", fr: "Panama" },
  PE: { es: "Perú", fr: "Pérou" },
  PF: { es: "Polinesia Francesa", fr: "Polynésie française" },
  PG: { es: "Papúa Nueva Guinea", fr: "Papouasie-Nouvelle-Guinée" },
  PH: { es: "Filipinas", fr: "Philippines" },
  PK: { es: "Pakistán", fr: "Pakistan" },
  PL: { es: "Polonia", fr: "Pologne" },
  PM: { es: "San Pedro y Miquelón", fr: "Saint-Pierre-et-Miquelon" },
  PN: { es: "Islas Pitcairn", fr: "Îles Pitcairn" },
  PR: { es: "Puerto Rico", fr: "Porto Rico" },
  PS: { es: "Palestina", fr: "Palestine" },
  PT: { es: "Portugal", fr: "Portugal" },
  PW: { es: "Palaos", fr: "Palaos" },
  PY: { es: "Paraguay", fr: "Paraguay" },
  QA: { es: "Catar", fr: "Qatar" },
  RE: { es: "Reunión", fr: "La Réunion" },
  RO: { es: "Rumanía", fr: "Roumanie" },
  RS: { es: "Serbia", fr: "Serbie" },
  RU: { es: "Rusia", fr: "Russie" },
  RW: { es: "Ruanda", fr: "Rwanda" },
  SA: { es: "Arabia Saudita", fr: "Arabie saoudite" },
  SB: { es: "Islas Salomón", fr: "Îles Salomon" },
  SC: { es: "Seychelles", fr: "Seychelles" },
  SD: { es: "Sudán", fr: "Soudan" },
  SE: { es: "Suecia", fr: "Suède" },
  SG: { es: "Singapur", fr: "Singapour" },
  SH: { es: "Santa Elena", fr: "Sainte-Hélène" },
  SI: { es: "Eslovenia", fr: "Slovénie" },
  SJ: { es: "Svalbard y Jan Mayen", fr: "Svalbard et Jan Mayen" },
  SK: { es: "Eslovaquia", fr: "Slovaquie" },
  SL: { es: "Sierra Leona", fr: "Sierra Leone" },
  SM: { es: "San Marino", fr: "Saint-Marin" },
  SN: { es: "Senegal", fr: "Sénégal" },
  SO: { es: "Somalia", fr: "Somalie" },
  SR: { es: "Surinam", fr: "Suriname" },
  SS: { es: "Sudán del Sur", fr: "Soudan du Sud" },
  ST: { es: "Santo Tomé y Príncipe", fr: "Sao Tomé-et-Príncipe" },
  SV: { es: "El Salvador", fr: "Salvador" },
  SX: { es: "Sint Maarten", fr: "Sint Maarten" },
  SY: { es: "Siria", fr: "Syrie" },
  SZ: { es: "Esuatini", fr: "Eswatini" },
  TC: { es: "Islas Turcas y Caicos", fr: "Îles Turques-et-Caïques" },
  TD: { es: "Chad", fr: "Tchad" },
  TF: { es: "Territorios Australes Franceses", fr: "Terres australes françaises" },
  TG: { es: "Togo", fr: "Togo" },
  TH: { es: "Tailandia", fr: "Thaïlande" },
  TJ: { es: "Tayikistán", fr: "Tadjikistan" },
  TK: { es: "Tokelau", fr: "Tokelau" },
  TL: { es: "Timor Oriental", fr: "Timor oriental" },
  TM: { es: "Turkmenistán", fr: "Turkménistan" },
  TN: { es: "Túnez", fr: "Tunisie" },
  TO: { es: "Tonga", fr: "Tonga" },
  TR: { es: "Turquía", fr: "Turquie" },
  TT: { es: "Trinidad y Tobago", fr: "Trinité-et-Tobago" },
  TV: { es: "Tuvalu", fr: "Tuvalu" },
  TW: { es: "Taiwán", fr: "Taïwan" },
  TZ: { es: "Tanzania", fr: "Tanzanie" },
  UA: { es: "Ucrania", fr: "Ukraine" },
  UG: { es: "Uganda", fr: "Ouganda" },
  UM: { es: "Islas Ultramarinas de EE.UU.", fr: "Îles mineures éloignées des États-Unis" },
  US: { es: "Estados Unidos", fr: "États-Unis" },
  UY: { es: "Uruguay", fr: "Uruguay" },
  UZ: { es: "Uzbekistán", fr: "Ouzbékistan" },
  VA: { es: "Ciudad del Vaticano", fr: "Vatican" },
  VC: { es: "San Vicente y las Granadinas", fr: "Saint-Vincent-et-les-Grenadines" },
  VE: { es: "Venezuela", fr: "Venezuela" },
  VG: { es: "Islas Vírgenes Británicas", fr: "Îles Vierges britanniques" },
  VI: { es: "Islas Vírgenes de EE.UU.", fr: "Îles Vierges des États-Unis" },
  VN: { es: "Vietnam", fr: "Viêt Nam" },
  VU: { es: "Vanuatu", fr: "Vanuatu" },
  WF: { es: "Wallis y Futuna", fr: "Wallis-et-Futuna" },
  WS: { es: "Samoa", fr: "Samoa" },
  XK: { es: "Kosovo", fr: "Kosovo" },
  YE: { es: "Yemen", fr: "Yémen" },
  YT: { es: "Mayotte", fr: "Mayotte" },
  ZA: { es: "Sudáfrica", fr: "Afrique du Sud" },
  ZM: { es: "Zambia", fr: "Zambie" },
  ZW: { es: "Zimbabue", fr: "Zimbabwe" },
};
